/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 03-Aug-2017 19:17:40
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */

/*
 * Expected path to tmwtypes.h
 * D:\Program Files\MATLAB\R2015a\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int TAP_SIZE = 11;
float TAP[11] = {
    0.01459853537,  0.03062995523,  0.07260075957,   0.1244795322,   0.1664503366,
     0.1824817657,   0.1664503366,   0.1244795322,  0.07260075957,  0.03062995523,
    0.01459853537
};
