/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.5 and the Signal Processing Toolbox 7.0.
 * Generated on: 22-Jul-2017 14:38:22
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 30
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2015a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 30;
const real32_T B[30] = {
  0.0005415165797, 0.001727426774, 0.003113061655, 0.003883380443, 0.002264012117,
  -0.003352924949, -0.01260423567,  -0.0218139533, -0.02428940125, -0.01267496031,
    0.01740843058,  0.06416342407,     0.11868231,   0.1671814919,   0.1957704276,
     0.1957704276,   0.1671814919,     0.11868231,  0.06416342407,  0.01740843058,
   -0.01267496031, -0.02428940125,  -0.0218139533, -0.01260423567,-0.003352924949,
   0.002264012117, 0.003883380443, 0.003113061655, 0.001727426774,0.0005415165797
};
